// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package config

import (
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi/config"
)

// The access token for API operations.
func GetAccessToken(ctx *pulumi.Context) string {
	return config.Get(ctx, "vra:accessToken")
}

// Specify whether to validate TLS certificates.
func GetInsecure(ctx *pulumi.Context) bool {
	return config.GetBool(ctx, "vra:insecure")
}

// Specify timeout for how often to reauthorize the access token
func GetReauthorizeTimeout(ctx *pulumi.Context) string {
	return config.Get(ctx, "vra:reauthorizeTimeout")
}

// The refresh token for API operations.
func GetRefreshToken(ctx *pulumi.Context) string {
	return config.Get(ctx, "vra:refreshToken")
}

// The base url for API operations.
func GetUrl(ctx *pulumi.Context) string {
	return config.Get(ctx, "vra:url")
}
