// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace schmidtw.Vra
{
    public static class GetRegionEnumerationAws
    {
        /// <summary>
        /// {{% examples %}}
        /// ## Example Usage
        /// {{% example %}}
        /// ### S
        /// 
        /// This is an example of how to lookup a region enumeration data source for AWS cloud account.
        /// 
        /// **Region enumeration data source for AWS, by the AWS account access key and secret key:**
        /// ```csharp
        /// using System.Collections.Generic;
        /// using Pulumi;
        /// using Vra = Pulumi.Vra;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var @this = Vra.GetRegionEnumerationAws.Invoke(new()
        ///     {
        ///         AccessKey = @var.Access_key,
        ///         SecretKey = @var.Secret_key,
        ///     });
        /// 
        /// });
        /// ```
        /// 
        /// The region enumeration data source for AWS cloud account supports the following arguments:
        /// {{% /example %}}
        /// {{% /examples %}}
        /// </summary>
        public static Task<GetRegionEnumerationAwsResult> InvokeAsync(GetRegionEnumerationAwsArgs args, InvokeOptions? options = null)
            => Pulumi.Deployment.Instance.InvokeAsync<GetRegionEnumerationAwsResult>("vra:index/getRegionEnumerationAws:getRegionEnumerationAws", args ?? new GetRegionEnumerationAwsArgs(), options.WithDefaults());

        /// <summary>
        /// {{% examples %}}
        /// ## Example Usage
        /// {{% example %}}
        /// ### S
        /// 
        /// This is an example of how to lookup a region enumeration data source for AWS cloud account.
        /// 
        /// **Region enumeration data source for AWS, by the AWS account access key and secret key:**
        /// ```csharp
        /// using System.Collections.Generic;
        /// using Pulumi;
        /// using Vra = Pulumi.Vra;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var @this = Vra.GetRegionEnumerationAws.Invoke(new()
        ///     {
        ///         AccessKey = @var.Access_key,
        ///         SecretKey = @var.Secret_key,
        ///     });
        /// 
        /// });
        /// ```
        /// 
        /// The region enumeration data source for AWS cloud account supports the following arguments:
        /// {{% /example %}}
        /// {{% /examples %}}
        /// </summary>
        public static Output<GetRegionEnumerationAwsResult> Invoke(GetRegionEnumerationAwsInvokeArgs args, InvokeOptions? options = null)
            => Pulumi.Deployment.Instance.Invoke<GetRegionEnumerationAwsResult>("vra:index/getRegionEnumerationAws:getRegionEnumerationAws", args ?? new GetRegionEnumerationAwsInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetRegionEnumerationAwsArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// Aws Access key ID.
        /// </summary>
        [Input("accessKey", required: true)]
        public string AccessKey { get; set; } = null!;

        /// <summary>
        /// Aws Secret Access Key.
        /// </summary>
        [Input("secretKey", required: true)]
        public string SecretKey { get; set; } = null!;

        public GetRegionEnumerationAwsArgs()
        {
        }
        public static new GetRegionEnumerationAwsArgs Empty => new GetRegionEnumerationAwsArgs();
    }

    public sealed class GetRegionEnumerationAwsInvokeArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// Aws Access key ID.
        /// </summary>
        [Input("accessKey", required: true)]
        public Input<string> AccessKey { get; set; } = null!;

        /// <summary>
        /// Aws Secret Access Key.
        /// </summary>
        [Input("secretKey", required: true)]
        public Input<string> SecretKey { get; set; } = null!;

        public GetRegionEnumerationAwsInvokeArgs()
        {
        }
        public static new GetRegionEnumerationAwsInvokeArgs Empty => new GetRegionEnumerationAwsInvokeArgs();
    }


    [OutputType]
    public sealed class GetRegionEnumerationAwsResult
    {
        public readonly string AccessKey;
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// A set of Region names to enable provisioning on. Example: us-east-2, ap-northeast-1
        /// </summary>
        public readonly ImmutableArray<string> Regions;
        public readonly string SecretKey;

        [OutputConstructor]
        private GetRegionEnumerationAwsResult(
            string accessKey,

            string id,

            ImmutableArray<string> regions,

            string secretKey)
        {
            AccessKey = accessKey;
            Id = id;
            Regions = regions;
            SecretKey = secretKey;
        }
    }
}
