// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Vra.Project.Inputs
{

    public sealed class ProjectMemberRoleArgs : global::Pulumi.ResourceArgs
    {
        [Input("email", required: true)]
        public Input<string> Email { get; set; } = null!;

        [Input("type")]
        public Input<string>? Type { get; set; }

        public ProjectMemberRoleArgs()
        {
        }
        public static new ProjectMemberRoleArgs Empty => new ProjectMemberRoleArgs();
    }
}
