// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package catalog

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// This data source provides information about a catalog item in vRA.
//
// ## Example Usage
// ### S
//
// This is an example of how to get a vRA catalog item by its name.
//
// ```go
// package main
//
// import (
// 	"github.com/pulumi/pulumi-vra/sdk/go/vra/catalog"
// 	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
// 	"github.com/pulumiverse/pulumi-vra/sdk/go/vra/catalog"
// )
//
// func main() {
// 	pulumi.Run(func(ctx *pulumi.Context) error {
// 		_, err := catalog.GetItem(ctx, &catalog.GetItemArgs{
// 			Name:           pulumi.StringRef(_var.Catalog_item_name),
// 			ExpandVersions: pulumi.BoolRef(true),
// 		}, nil)
// 		if err != nil {
// 			return err
// 		}
// 		return nil
// 	})
// }
// ```
//
// This is an example of how to get a vRA catalog item by its id.
//
// ```go
// package main
//
// import (
// 	"github.com/pulumi/pulumi-vra/sdk/go/vra/catalog"
// 	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
// 	"github.com/pulumiverse/pulumi-vra/sdk/go/vra/catalog"
// )
//
// func main() {
// 	pulumi.Run(func(ctx *pulumi.Context) error {
// 		_, err := catalog.GetItem(ctx, &catalog.GetItemArgs{
// 			Id:             pulumi.StringRef(_var.Catalog_item_id),
// 			ExpandVersions: pulumi.BoolRef(true),
// 		}, nil)
// 		if err != nil {
// 			return err
// 		}
// 		return nil
// 	})
// }
// ```
func GetItem(ctx *pulumi.Context, args *GetItemArgs, opts ...pulumi.InvokeOption) (*GetItemResult, error) {
	opts = pkgInvokeDefaultOpts(opts)
	var rv GetItemResult
	err := ctx.Invoke("vra:catalog/getItem:getItem", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getItem.
type GetItemArgs struct {
	// Flag to indicate whether to expand detailed project data for the catalog item.
	ExpandProjects *bool `pulumi:"expandProjects"`
	// Flag to indicate whether to expand detailed versions of the catalog item.
	ExpandVersions *bool `pulumi:"expandVersions"`
	// The id of catalog item. One of `id`, or `name` must be provided.
	Id *string `pulumi:"id"`
	// Name of the catalog item. One of `id`, or `name` must be provided.
	Name *string `pulumi:"name"`
}

// A collection of values returned by getItem.
type GetItemResult struct {
	// Date-time when catalog item version was created at.
	CreatedAt string `pulumi:"createdAt"`
	// The user the entity was created by.
	CreatedBy string `pulumi:"createdBy"`
	// A human-friendly description.
	Description    string `pulumi:"description"`
	ExpandProjects *bool  `pulumi:"expandProjects"`
	ExpandVersions *bool  `pulumi:"expandVersions"`
	// Id of the catalog item version.
	Id string `pulumi:"id"`
	// Date-time when the entity was last updated.
	LastUpdatedAt string `pulumi:"lastUpdatedAt"`
	// The user the entity was last updated by.
	LastUpdatedBy string `pulumi:"lastUpdatedBy"`
	// Name of the entity.
	Name string `pulumi:"name"`
	// List of associated project IDs that can be used for requesting this catalog item.
	ProjectIds []string `pulumi:"projectIds"`
	// List of associated projects that can be used for requesting this catalog item.
	Projects []GetItemProject `pulumi:"projects"`
	// Json schema describing request parameters, a simplified version of http://json-schema.org/latest/json-schema-validation.html#rfc.section.5
	Schema string `pulumi:"schema"`
	// LibraryItem source ID.
	SourceId string `pulumi:"sourceId"`
	// LibraryItem source name.
	SourceName string        `pulumi:"sourceName"`
	Types      []GetItemType `pulumi:"types"`
	// Catalog item versions.
	Versions []GetItemVersion `pulumi:"versions"`
}

func GetItemOutput(ctx *pulumi.Context, args GetItemOutputArgs, opts ...pulumi.InvokeOption) GetItemResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (GetItemResult, error) {
			args := v.(GetItemArgs)
			r, err := GetItem(ctx, &args, opts...)
			var s GetItemResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(GetItemResultOutput)
}

// A collection of arguments for invoking getItem.
type GetItemOutputArgs struct {
	// Flag to indicate whether to expand detailed project data for the catalog item.
	ExpandProjects pulumi.BoolPtrInput `pulumi:"expandProjects"`
	// Flag to indicate whether to expand detailed versions of the catalog item.
	ExpandVersions pulumi.BoolPtrInput `pulumi:"expandVersions"`
	// The id of catalog item. One of `id`, or `name` must be provided.
	Id pulumi.StringPtrInput `pulumi:"id"`
	// Name of the catalog item. One of `id`, or `name` must be provided.
	Name pulumi.StringPtrInput `pulumi:"name"`
}

func (GetItemOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetItemArgs)(nil)).Elem()
}

// A collection of values returned by getItem.
type GetItemResultOutput struct{ *pulumi.OutputState }

func (GetItemResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetItemResult)(nil)).Elem()
}

func (o GetItemResultOutput) ToGetItemResultOutput() GetItemResultOutput {
	return o
}

func (o GetItemResultOutput) ToGetItemResultOutputWithContext(ctx context.Context) GetItemResultOutput {
	return o
}

// Date-time when catalog item version was created at.
func (o GetItemResultOutput) CreatedAt() pulumi.StringOutput {
	return o.ApplyT(func(v GetItemResult) string { return v.CreatedAt }).(pulumi.StringOutput)
}

// The user the entity was created by.
func (o GetItemResultOutput) CreatedBy() pulumi.StringOutput {
	return o.ApplyT(func(v GetItemResult) string { return v.CreatedBy }).(pulumi.StringOutput)
}

// A human-friendly description.
func (o GetItemResultOutput) Description() pulumi.StringOutput {
	return o.ApplyT(func(v GetItemResult) string { return v.Description }).(pulumi.StringOutput)
}

func (o GetItemResultOutput) ExpandProjects() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v GetItemResult) *bool { return v.ExpandProjects }).(pulumi.BoolPtrOutput)
}

func (o GetItemResultOutput) ExpandVersions() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v GetItemResult) *bool { return v.ExpandVersions }).(pulumi.BoolPtrOutput)
}

// Id of the catalog item version.
func (o GetItemResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetItemResult) string { return v.Id }).(pulumi.StringOutput)
}

// Date-time when the entity was last updated.
func (o GetItemResultOutput) LastUpdatedAt() pulumi.StringOutput {
	return o.ApplyT(func(v GetItemResult) string { return v.LastUpdatedAt }).(pulumi.StringOutput)
}

// The user the entity was last updated by.
func (o GetItemResultOutput) LastUpdatedBy() pulumi.StringOutput {
	return o.ApplyT(func(v GetItemResult) string { return v.LastUpdatedBy }).(pulumi.StringOutput)
}

// Name of the entity.
func (o GetItemResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v GetItemResult) string { return v.Name }).(pulumi.StringOutput)
}

// List of associated project IDs that can be used for requesting this catalog item.
func (o GetItemResultOutput) ProjectIds() pulumi.StringArrayOutput {
	return o.ApplyT(func(v GetItemResult) []string { return v.ProjectIds }).(pulumi.StringArrayOutput)
}

// List of associated projects that can be used for requesting this catalog item.
func (o GetItemResultOutput) Projects() GetItemProjectArrayOutput {
	return o.ApplyT(func(v GetItemResult) []GetItemProject { return v.Projects }).(GetItemProjectArrayOutput)
}

// Json schema describing request parameters, a simplified version of http://json-schema.org/latest/json-schema-validation.html#rfc.section.5
func (o GetItemResultOutput) Schema() pulumi.StringOutput {
	return o.ApplyT(func(v GetItemResult) string { return v.Schema }).(pulumi.StringOutput)
}

// LibraryItem source ID.
func (o GetItemResultOutput) SourceId() pulumi.StringOutput {
	return o.ApplyT(func(v GetItemResult) string { return v.SourceId }).(pulumi.StringOutput)
}

// LibraryItem source name.
func (o GetItemResultOutput) SourceName() pulumi.StringOutput {
	return o.ApplyT(func(v GetItemResult) string { return v.SourceName }).(pulumi.StringOutput)
}

func (o GetItemResultOutput) Types() GetItemTypeArrayOutput {
	return o.ApplyT(func(v GetItemResult) []GetItemType { return v.Types }).(GetItemTypeArrayOutput)
}

// Catalog item versions.
func (o GetItemResultOutput) Versions() GetItemVersionArrayOutput {
	return o.ApplyT(func(v GetItemResult) []GetItemVersion { return v.Versions }).(GetItemVersionArrayOutput)
}

func init() {
	pulumi.RegisterOutputType(GetItemResultOutput{})
}
