// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package network

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// ## Example Usage
// ### S
// This is an example of how to create a network profile resource.
//
// **Network profile data source by its id:**
//
// ```go
// package main
//
// import (
//
//	"fmt"
//
//	"github.com/pulumi/pulumi-vra/sdk/go/vra/network"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//	"github.com/pulumiverse/pulumi-vra/sdk/go/vra/network"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := network.LookupProfile(ctx, &network.LookupProfileArgs{
//				Filter: pulumi.StringRef(fmt.Sprintf("name eq '%v'", vra_network_profile.This.Name)),
//			}, nil)
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
//
// **Vra network profile data source filter by region id:**
//
// ```go
// package main
//
// import (
//
//	"fmt"
//
//	"github.com/pulumi/pulumi-vra/sdk/go/vra/network"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//	"github.com/pulumiverse/pulumi-vra/sdk/go/vra/network"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := network.LookupProfile(ctx, &network.LookupProfileArgs{
//				Filter: pulumi.StringRef(fmt.Sprintf("regionId eq '%v'", data.Vra_region.This.Id)),
//			}, nil)
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
//
// A network profile data source supports the following arguments:
func LookupProfile(ctx *pulumi.Context, args *LookupProfileArgs, opts ...pulumi.InvokeOption) (*LookupProfileResult, error) {
	opts = pkgInvokeDefaultOpts(opts)
	var rv LookupProfileResult
	err := ctx.Invoke("vra:network/getProfile:getProfile", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getProfile.
type LookupProfileArgs struct {
	// Filter query string that is supported by vRA multi-cloud IaaS API. Example: regionId eq '<regionId>' and cloudAccountId eq '<cloudAccountId>'.
	Filter *string `pulumi:"filter"`
	// The id of the image profile instance.
	Id *string `pulumi:"id"`
	// The Id of the fabric network used for outbound access.
	IsolatedExternalFabricNetworkId *string `pulumi:"isolatedExternalFabricNetworkId"`
	// The Id of the network domain used for creating isolated networks.
	IsolatedNetworkDomainId *string `pulumi:"isolatedNetworkDomainId"`
	// A set of tag keys and optional values that were set on this Network Profile.
	// example:[ { "key" : "ownedBy", "value": "Rainpole" } ]
	Tags []GetProfileTag `pulumi:"tags"`
}

// A collection of values returned by getProfile.
type LookupProfileResult struct {
	// Additional properties that may be used to extend the Network Profile object that is produced from this specification. For isolationType security group, datastoreId identifies the Compute Resource Edge datastore. computeCluster and resourcePoolId identify the Compute Resource Edge cluster. For isolationType subnet, distributedLogicalRouterStateLink identifies the on-demand network distributed local router. onDemandNetworkIPAssignmentType identifies the on-demand network IP range assignment type static, dynamic, or mixed.
	CustomProperties map[string]interface{} `pulumi:"customProperties"`
	// A human-friendly description.
	Description string `pulumi:"description"`
	// The external regionId of the resource.
	ExternalRegionId string `pulumi:"externalRegionId"`
	// A list of fabric network Ids which are assigned to the network profile.
	// example:[ "6543" ]
	FabricNetworkIds                []string `pulumi:"fabricNetworkIds"`
	Filter                          *string  `pulumi:"filter"`
	Id                              string   `pulumi:"id"`
	IsolatedExternalFabricNetworkId *string  `pulumi:"isolatedExternalFabricNetworkId"`
	// The CIDR prefix length to be used for the isolated networks that are created with the network profile.
	IsolatedNetworkCidrPrefix int `pulumi:"isolatedNetworkCidrPrefix"`
	// CIDR of the isolation network domain.
	IsolatedNetworkDomainCidr string  `pulumi:"isolatedNetworkDomainCidr"`
	IsolatedNetworkDomainId   *string `pulumi:"isolatedNetworkDomainId"`
	// Specifies the isolation type e.g. none, subnet or security group
	IsolationType string `pulumi:"isolationType"`
	// HATEOAS of the entity
	Links []GetProfileLink `pulumi:"links"`
	// A human-friendly name used as an identifier in APIs that support this option.
	Name string `pulumi:"name"`
	// The id of the organization this entity belongs to.
	OrganizationId string `pulumi:"organizationId"`
	// Email of the user that owns the entity.
	Owner string `pulumi:"owner"`
	// The id of the region for which this profile is defined as in vRealize Automation(vRA).
	RegionId string `pulumi:"regionId"`
	// A list of security group Ids which are assigned to the network profile.
	// example:[ "6545" ]
	SecurityGroupIds []string `pulumi:"securityGroupIds"`
	// A set of tag keys and optional values that were set on this Network Profile.
	// example:[ { "key" : "ownedBy", "value": "Rainpole" } ]
	Tags []GetProfileTag `pulumi:"tags"`
	// Date when the entity was last updated. The date is ISO 8601 and UTC.
	UpdatedAt string `pulumi:"updatedAt"`
}

func LookupProfileOutput(ctx *pulumi.Context, args LookupProfileOutputArgs, opts ...pulumi.InvokeOption) LookupProfileResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (LookupProfileResult, error) {
			args := v.(LookupProfileArgs)
			r, err := LookupProfile(ctx, &args, opts...)
			var s LookupProfileResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(LookupProfileResultOutput)
}

// A collection of arguments for invoking getProfile.
type LookupProfileOutputArgs struct {
	// Filter query string that is supported by vRA multi-cloud IaaS API. Example: regionId eq '<regionId>' and cloudAccountId eq '<cloudAccountId>'.
	Filter pulumi.StringPtrInput `pulumi:"filter"`
	// The id of the image profile instance.
	Id pulumi.StringPtrInput `pulumi:"id"`
	// The Id of the fabric network used for outbound access.
	IsolatedExternalFabricNetworkId pulumi.StringPtrInput `pulumi:"isolatedExternalFabricNetworkId"`
	// The Id of the network domain used for creating isolated networks.
	IsolatedNetworkDomainId pulumi.StringPtrInput `pulumi:"isolatedNetworkDomainId"`
	// A set of tag keys and optional values that were set on this Network Profile.
	// example:[ { "key" : "ownedBy", "value": "Rainpole" } ]
	Tags GetProfileTagArrayInput `pulumi:"tags"`
}

func (LookupProfileOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupProfileArgs)(nil)).Elem()
}

// A collection of values returned by getProfile.
type LookupProfileResultOutput struct{ *pulumi.OutputState }

func (LookupProfileResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupProfileResult)(nil)).Elem()
}

func (o LookupProfileResultOutput) ToLookupProfileResultOutput() LookupProfileResultOutput {
	return o
}

func (o LookupProfileResultOutput) ToLookupProfileResultOutputWithContext(ctx context.Context) LookupProfileResultOutput {
	return o
}

// Additional properties that may be used to extend the Network Profile object that is produced from this specification. For isolationType security group, datastoreId identifies the Compute Resource Edge datastore. computeCluster and resourcePoolId identify the Compute Resource Edge cluster. For isolationType subnet, distributedLogicalRouterStateLink identifies the on-demand network distributed local router. onDemandNetworkIPAssignmentType identifies the on-demand network IP range assignment type static, dynamic, or mixed.
func (o LookupProfileResultOutput) CustomProperties() pulumi.MapOutput {
	return o.ApplyT(func(v LookupProfileResult) map[string]interface{} { return v.CustomProperties }).(pulumi.MapOutput)
}

// A human-friendly description.
func (o LookupProfileResultOutput) Description() pulumi.StringOutput {
	return o.ApplyT(func(v LookupProfileResult) string { return v.Description }).(pulumi.StringOutput)
}

// The external regionId of the resource.
func (o LookupProfileResultOutput) ExternalRegionId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupProfileResult) string { return v.ExternalRegionId }).(pulumi.StringOutput)
}

// A list of fabric network Ids which are assigned to the network profile.
// example:[ "6543" ]
func (o LookupProfileResultOutput) FabricNetworkIds() pulumi.StringArrayOutput {
	return o.ApplyT(func(v LookupProfileResult) []string { return v.FabricNetworkIds }).(pulumi.StringArrayOutput)
}

func (o LookupProfileResultOutput) Filter() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupProfileResult) *string { return v.Filter }).(pulumi.StringPtrOutput)
}

func (o LookupProfileResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupProfileResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o LookupProfileResultOutput) IsolatedExternalFabricNetworkId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupProfileResult) *string { return v.IsolatedExternalFabricNetworkId }).(pulumi.StringPtrOutput)
}

// The CIDR prefix length to be used for the isolated networks that are created with the network profile.
func (o LookupProfileResultOutput) IsolatedNetworkCidrPrefix() pulumi.IntOutput {
	return o.ApplyT(func(v LookupProfileResult) int { return v.IsolatedNetworkCidrPrefix }).(pulumi.IntOutput)
}

// CIDR of the isolation network domain.
func (o LookupProfileResultOutput) IsolatedNetworkDomainCidr() pulumi.StringOutput {
	return o.ApplyT(func(v LookupProfileResult) string { return v.IsolatedNetworkDomainCidr }).(pulumi.StringOutput)
}

func (o LookupProfileResultOutput) IsolatedNetworkDomainId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupProfileResult) *string { return v.IsolatedNetworkDomainId }).(pulumi.StringPtrOutput)
}

// Specifies the isolation type e.g. none, subnet or security group
func (o LookupProfileResultOutput) IsolationType() pulumi.StringOutput {
	return o.ApplyT(func(v LookupProfileResult) string { return v.IsolationType }).(pulumi.StringOutput)
}

// HATEOAS of the entity
func (o LookupProfileResultOutput) Links() GetProfileLinkArrayOutput {
	return o.ApplyT(func(v LookupProfileResult) []GetProfileLink { return v.Links }).(GetProfileLinkArrayOutput)
}

// A human-friendly name used as an identifier in APIs that support this option.
func (o LookupProfileResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v LookupProfileResult) string { return v.Name }).(pulumi.StringOutput)
}

// The id of the organization this entity belongs to.
func (o LookupProfileResultOutput) OrganizationId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupProfileResult) string { return v.OrganizationId }).(pulumi.StringOutput)
}

// Email of the user that owns the entity.
func (o LookupProfileResultOutput) Owner() pulumi.StringOutput {
	return o.ApplyT(func(v LookupProfileResult) string { return v.Owner }).(pulumi.StringOutput)
}

// The id of the region for which this profile is defined as in vRealize Automation(vRA).
func (o LookupProfileResultOutput) RegionId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupProfileResult) string { return v.RegionId }).(pulumi.StringOutput)
}

// A list of security group Ids which are assigned to the network profile.
// example:[ "6545" ]
func (o LookupProfileResultOutput) SecurityGroupIds() pulumi.StringArrayOutput {
	return o.ApplyT(func(v LookupProfileResult) []string { return v.SecurityGroupIds }).(pulumi.StringArrayOutput)
}

// A set of tag keys and optional values that were set on this Network Profile.
// example:[ { "key" : "ownedBy", "value": "Rainpole" } ]
func (o LookupProfileResultOutput) Tags() GetProfileTagArrayOutput {
	return o.ApplyT(func(v LookupProfileResult) []GetProfileTag { return v.Tags }).(GetProfileTagArrayOutput)
}

// Date when the entity was last updated. The date is ISO 8601 and UTC.
func (o LookupProfileResultOutput) UpdatedAt() pulumi.StringOutput {
	return o.ApplyT(func(v LookupProfileResult) string { return v.UpdatedAt }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupProfileResultOutput{})
}
