// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package region

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// ## Example Usage
// ### S
//
// This is an example of how to lookup a region enumeration data source for AWS cloud account.
//
// **Region enumeration data source for AWS, by the AWS account access key and secret key:**
// ```go
// package main
//
// import (
//
//	"github.com/pulumi/pulumi-vra/sdk/go/vra/region"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//	"github.com/pulumiverse/pulumi-vra/sdk/go/vra/region"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := region.GetEnumerationAws(ctx, &region.GetEnumerationAwsArgs{
//				AccessKey: _var.Access_key,
//				SecretKey: _var.Secret_key,
//			}, nil)
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
//
// The region enumeration data source for AWS cloud account supports the following arguments:
func GetEnumerationAws(ctx *pulumi.Context, args *GetEnumerationAwsArgs, opts ...pulumi.InvokeOption) (*GetEnumerationAwsResult, error) {
	opts = pkgInvokeDefaultOpts(opts)
	var rv GetEnumerationAwsResult
	err := ctx.Invoke("vra:region/getEnumerationAws:getEnumerationAws", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getEnumerationAws.
type GetEnumerationAwsArgs struct {
	// Aws Access key ID.
	AccessKey string `pulumi:"accessKey"`
	// Aws Secret Access Key.
	SecretKey string `pulumi:"secretKey"`
}

// A collection of values returned by getEnumerationAws.
type GetEnumerationAwsResult struct {
	AccessKey string `pulumi:"accessKey"`
	// The provider-assigned unique ID for this managed resource.
	Id string `pulumi:"id"`
	// A set of Region names to enable provisioning on. Example: us-east-2, ap-northeast-1
	Regions   []string `pulumi:"regions"`
	SecretKey string   `pulumi:"secretKey"`
}

func GetEnumerationAwsOutput(ctx *pulumi.Context, args GetEnumerationAwsOutputArgs, opts ...pulumi.InvokeOption) GetEnumerationAwsResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (GetEnumerationAwsResult, error) {
			args := v.(GetEnumerationAwsArgs)
			r, err := GetEnumerationAws(ctx, &args, opts...)
			var s GetEnumerationAwsResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(GetEnumerationAwsResultOutput)
}

// A collection of arguments for invoking getEnumerationAws.
type GetEnumerationAwsOutputArgs struct {
	// Aws Access key ID.
	AccessKey pulumi.StringInput `pulumi:"accessKey"`
	// Aws Secret Access Key.
	SecretKey pulumi.StringInput `pulumi:"secretKey"`
}

func (GetEnumerationAwsOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetEnumerationAwsArgs)(nil)).Elem()
}

// A collection of values returned by getEnumerationAws.
type GetEnumerationAwsResultOutput struct{ *pulumi.OutputState }

func (GetEnumerationAwsResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetEnumerationAwsResult)(nil)).Elem()
}

func (o GetEnumerationAwsResultOutput) ToGetEnumerationAwsResultOutput() GetEnumerationAwsResultOutput {
	return o
}

func (o GetEnumerationAwsResultOutput) ToGetEnumerationAwsResultOutputWithContext(ctx context.Context) GetEnumerationAwsResultOutput {
	return o
}

func (o GetEnumerationAwsResultOutput) AccessKey() pulumi.StringOutput {
	return o.ApplyT(func(v GetEnumerationAwsResult) string { return v.AccessKey }).(pulumi.StringOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o GetEnumerationAwsResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetEnumerationAwsResult) string { return v.Id }).(pulumi.StringOutput)
}

// A set of Region names to enable provisioning on. Example: us-east-2, ap-northeast-1
func (o GetEnumerationAwsResultOutput) Regions() pulumi.StringArrayOutput {
	return o.ApplyT(func(v GetEnumerationAwsResult) []string { return v.Regions }).(pulumi.StringArrayOutput)
}

func (o GetEnumerationAwsResultOutput) SecretKey() pulumi.StringOutput {
	return o.ApplyT(func(v GetEnumerationAwsResult) string { return v.SecretKey }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(GetEnumerationAwsResultOutput{})
}
