// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package vra

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// This data source provides information about a cloud template (blueprint) version in vRA.
//
// ## Example Usage
// ### S
//
// ```go
// package main
//
// import (
//
//	"github.com/pulumi/pulumi-vra/sdk/go/vra"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//	"github.com/schmidtw/pulumi-vra/sdk/go/vra"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := vra.LookupBlueprintVersion(ctx, &GetBlueprintVersionArgs{
//				BlueprintId: _var.Blueprint_id,
//				Id:          _var.Blueprint_version_id,
//			}, nil)
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
func LookupBlueprintVersion(ctx *pulumi.Context, args *LookupBlueprintVersionArgs, opts ...pulumi.InvokeOption) (*LookupBlueprintVersionResult, error) {
	opts = pkgInvokeDefaultOpts(opts)
	var rv LookupBlueprintVersionResult
	err := ctx.Invoke("vra:index/getBlueprintVersion:getBlueprintVersion", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getBlueprintVersion.
type LookupBlueprintVersionArgs struct {
	// Name of the cloud template. One of `id` or `name` must be provided.
	BlueprintId string `pulumi:"blueprintId"`
	// The id of the cloud template version.
	Id string `pulumi:"id"`
}

// A collection of values returned by getBlueprintVersion.
type LookupBlueprintVersionResult struct {
	// Description of the cloud template.
	BlueprintDescription string `pulumi:"blueprintDescription"`
	BlueprintId          string `pulumi:"blueprintId"`
	// Blueprint YAML content.
	Content string `pulumi:"content"`
	// Date when the entity was created. The date is in ISO 6801 and UTC.
	CreatedAt string `pulumi:"createdAt"`
	// The user the entity was created by.
	CreatedBy string `pulumi:"createdBy"`
	// (Optional) Cloud template version description.
	Description string `pulumi:"description"`
	Id          string `pulumi:"id"`
	// Name of the cloud template version.
	Name string `pulumi:"name"`
	// The id of the organization this entity belongs to.
	OrgId string `pulumi:"orgId"`
	// The id of the project this entity belongs to.
	ProjectId string `pulumi:"projectId"`
	// The name of the project the entity belongs to.
	ProjectName string `pulumi:"projectName"`
	// Status of the cloud template. Supported values: `DRAFT`, `VERSIONED`, `RELEASED`.
	Status string `pulumi:"status"`
	// Date when the entity was last updated. The date is ISO 8601 and UTC.
	UpdatedAt string `pulumi:"updatedAt"`
	// The user the entity was last updated by.
	UpdatedBy string `pulumi:"updatedBy"`
	// Flag to indicate if the current content of the cloud template is valid.
	Valid string `pulumi:"valid"`
	// Cloud template version.
	Version string `pulumi:"version"`
	// Cloud template version change log.
	VersionChangeLog string `pulumi:"versionChangeLog"`
}

func LookupBlueprintVersionOutput(ctx *pulumi.Context, args LookupBlueprintVersionOutputArgs, opts ...pulumi.InvokeOption) LookupBlueprintVersionResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (LookupBlueprintVersionResult, error) {
			args := v.(LookupBlueprintVersionArgs)
			r, err := LookupBlueprintVersion(ctx, &args, opts...)
			var s LookupBlueprintVersionResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(LookupBlueprintVersionResultOutput)
}

// A collection of arguments for invoking getBlueprintVersion.
type LookupBlueprintVersionOutputArgs struct {
	// Name of the cloud template. One of `id` or `name` must be provided.
	BlueprintId pulumi.StringInput `pulumi:"blueprintId"`
	// The id of the cloud template version.
	Id pulumi.StringInput `pulumi:"id"`
}

func (LookupBlueprintVersionOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupBlueprintVersionArgs)(nil)).Elem()
}

// A collection of values returned by getBlueprintVersion.
type LookupBlueprintVersionResultOutput struct{ *pulumi.OutputState }

func (LookupBlueprintVersionResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupBlueprintVersionResult)(nil)).Elem()
}

func (o LookupBlueprintVersionResultOutput) ToLookupBlueprintVersionResultOutput() LookupBlueprintVersionResultOutput {
	return o
}

func (o LookupBlueprintVersionResultOutput) ToLookupBlueprintVersionResultOutputWithContext(ctx context.Context) LookupBlueprintVersionResultOutput {
	return o
}

// Description of the cloud template.
func (o LookupBlueprintVersionResultOutput) BlueprintDescription() pulumi.StringOutput {
	return o.ApplyT(func(v LookupBlueprintVersionResult) string { return v.BlueprintDescription }).(pulumi.StringOutput)
}

func (o LookupBlueprintVersionResultOutput) BlueprintId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupBlueprintVersionResult) string { return v.BlueprintId }).(pulumi.StringOutput)
}

// Blueprint YAML content.
func (o LookupBlueprintVersionResultOutput) Content() pulumi.StringOutput {
	return o.ApplyT(func(v LookupBlueprintVersionResult) string { return v.Content }).(pulumi.StringOutput)
}

// Date when the entity was created. The date is in ISO 6801 and UTC.
func (o LookupBlueprintVersionResultOutput) CreatedAt() pulumi.StringOutput {
	return o.ApplyT(func(v LookupBlueprintVersionResult) string { return v.CreatedAt }).(pulumi.StringOutput)
}

// The user the entity was created by.
func (o LookupBlueprintVersionResultOutput) CreatedBy() pulumi.StringOutput {
	return o.ApplyT(func(v LookupBlueprintVersionResult) string { return v.CreatedBy }).(pulumi.StringOutput)
}

// (Optional) Cloud template version description.
func (o LookupBlueprintVersionResultOutput) Description() pulumi.StringOutput {
	return o.ApplyT(func(v LookupBlueprintVersionResult) string { return v.Description }).(pulumi.StringOutput)
}

func (o LookupBlueprintVersionResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupBlueprintVersionResult) string { return v.Id }).(pulumi.StringOutput)
}

// Name of the cloud template version.
func (o LookupBlueprintVersionResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v LookupBlueprintVersionResult) string { return v.Name }).(pulumi.StringOutput)
}

// The id of the organization this entity belongs to.
func (o LookupBlueprintVersionResultOutput) OrgId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupBlueprintVersionResult) string { return v.OrgId }).(pulumi.StringOutput)
}

// The id of the project this entity belongs to.
func (o LookupBlueprintVersionResultOutput) ProjectId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupBlueprintVersionResult) string { return v.ProjectId }).(pulumi.StringOutput)
}

// The name of the project the entity belongs to.
func (o LookupBlueprintVersionResultOutput) ProjectName() pulumi.StringOutput {
	return o.ApplyT(func(v LookupBlueprintVersionResult) string { return v.ProjectName }).(pulumi.StringOutput)
}

// Status of the cloud template. Supported values: `DRAFT`, `VERSIONED`, `RELEASED`.
func (o LookupBlueprintVersionResultOutput) Status() pulumi.StringOutput {
	return o.ApplyT(func(v LookupBlueprintVersionResult) string { return v.Status }).(pulumi.StringOutput)
}

// Date when the entity was last updated. The date is ISO 8601 and UTC.
func (o LookupBlueprintVersionResultOutput) UpdatedAt() pulumi.StringOutput {
	return o.ApplyT(func(v LookupBlueprintVersionResult) string { return v.UpdatedAt }).(pulumi.StringOutput)
}

// The user the entity was last updated by.
func (o LookupBlueprintVersionResultOutput) UpdatedBy() pulumi.StringOutput {
	return o.ApplyT(func(v LookupBlueprintVersionResult) string { return v.UpdatedBy }).(pulumi.StringOutput)
}

// Flag to indicate if the current content of the cloud template is valid.
func (o LookupBlueprintVersionResultOutput) Valid() pulumi.StringOutput {
	return o.ApplyT(func(v LookupBlueprintVersionResult) string { return v.Valid }).(pulumi.StringOutput)
}

// Cloud template version.
func (o LookupBlueprintVersionResultOutput) Version() pulumi.StringOutput {
	return o.ApplyT(func(v LookupBlueprintVersionResult) string { return v.Version }).(pulumi.StringOutput)
}

// Cloud template version change log.
func (o LookupBlueprintVersionResultOutput) VersionChangeLog() pulumi.StringOutput {
	return o.ApplyT(func(v LookupBlueprintVersionResult) string { return v.VersionChangeLog }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupBlueprintVersionResultOutput{})
}
