// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import { input as inputs, output as outputs } from "./types";
import * as utilities from "./utilities";

/**
 * Provides a VMware vRA vra.CloudAccountNsxt data source.
 *
 * ## Example Usage
 * ### S
 *
 * **NSX-T cloud account data source by its id:**
 *
 * This is an example of how to read the cloud account data source using its id.
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as vra from "@pulumi/vra";
 *
 * const this = vra.getCloudAccountNsxt({
 *     id: _var.vra_cloud_account_nsxt_id,
 * });
 * ```
 *
 * **NSX-T cloud account data source by its name:**
 *
 * This is an example of how to read the cloud account data source using its name.
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as vra from "@pulumi/vra";
 *
 * const this = vra.getCloudAccountNsxt({
 *     name: _var.vra_cloud_account_nsxt_name,
 * });
 * ```
 */
export function getCloudAccountNsxt(args?: GetCloudAccountNsxtArgs, opts?: pulumi.InvokeOptions): Promise<GetCloudAccountNsxtResult> {
    args = args || {};
    if (!opts) {
        opts = {}
    }

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
    return pulumi.runtime.invoke("vra:index/getCloudAccountNsxt:getCloudAccountNsxt", {
        "id": args.id,
        "name": args.name,
        "tags": args.tags,
    }, opts);
}

/**
 * A collection of arguments for invoking getCloudAccountNsxt.
 */
export interface GetCloudAccountNsxtArgs {
    /**
     * The id of this NSX-T cloud account.
     */
    id?: string;
    /**
     * The name of this NSX-T cloud account.
     */
    name?: string;
    /**
     * A set of tag keys and optional values that were set on this resource.
     * example:[ { "key" : "vmware", "value": "provider" } ]
     */
    tags?: inputs.GetCloudAccountNsxtTag[];
}

/**
 * A collection of values returned by getCloudAccountNsxt.
 */
export interface GetCloudAccountNsxtResult {
    /**
     * Cloud accounts associated with this cloud account.
     */
    readonly associatedCloudAccountIds: string[];
    /**
     * Date when the entity was created. The date is in ISO 6801 and UTC.
     */
    readonly createdAt: string;
    /**
     * Identifier of a data collector vm deployed in the on premise infrastructure.
     */
    readonly dcId: string;
    /**
     * A human-friendly description.
     */
    readonly description: string;
    /**
     * Host name for the NSX-T cloud account.
     */
    readonly hostname: string;
    readonly id: string;
    /**
     * HATEOAS of the entity.
     */
    readonly links: outputs.GetCloudAccountNsxtLink[];
    readonly managerMode: boolean;
    readonly name: string;
    /**
     * The id of the organization this entity belongs to.
     */
    readonly orgId: string;
    /**
     * Email of the user that owns the entity.
     */
    readonly owner: string;
    /**
     * A set of tag keys and optional values that were set on this resource.
     * example:[ { "key" : "vmware", "value": "provider" } ]
     */
    readonly tags: outputs.GetCloudAccountNsxtTag[];
    /**
     * Date when the entity was last updated. The date is ISO 8601 and UTC.
     */
    readonly updatedAt: string;
    /**
     * Username to authenticate with the cloud account.
     */
    readonly username: string;
}

export function getCloudAccountNsxtOutput(args?: GetCloudAccountNsxtOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetCloudAccountNsxtResult> {
    return pulumi.output(args).apply(a => getCloudAccountNsxt(a, opts))
}

/**
 * A collection of arguments for invoking getCloudAccountNsxt.
 */
export interface GetCloudAccountNsxtOutputArgs {
    /**
     * The id of this NSX-T cloud account.
     */
    id?: pulumi.Input<string>;
    /**
     * The name of this NSX-T cloud account.
     */
    name?: pulumi.Input<string>;
    /**
     * A set of tag keys and optional values that were set on this resource.
     * example:[ { "key" : "vmware", "value": "provider" } ]
     */
    tags?: pulumi.Input<pulumi.Input<inputs.GetCloudAccountNsxtTagArgs>[]>;
}
