// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Vra.Image.Inputs
{

    public sealed class GetProfileImageMappingConstraintArgs : global::Pulumi.InvokeArgs
    {
        [Input("expression", required: true)]
        public string Expression { get; set; } = null!;

        [Input("mandatory", required: true)]
        public bool Mandatory { get; set; }

        public GetProfileImageMappingConstraintArgs()
        {
        }
        public static new GetProfileImageMappingConstraintArgs Empty => new GetProfileImageMappingConstraintArgs();
    }
}
